// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user_api.proto

package com.example.asdfprotoproducer.java.user;

import com.example.asdfprotoproducer.java.notification.NotificationApi;

public final class UserApi {
  private UserApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.User)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The email.
     */
    String getEmail();
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     * @return Whether the notific field is set.
     */
    boolean hasNotific();
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     * @return The notific.
     */
    NotificationApi.Notification getNotific();
  }
  /**
   * <pre>
   * User contains all the personal details we know about the user.
   * </pre>
   *
   * Protobuf type {@code user.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageLite<
          User, User.Builder> implements
      // @@protoc_insertion_point(message_implements:user.User)
      UserOrBuilder {
    private User() {
      name_ = "";
      email_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private String name_;
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      return name_;
    }
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     */
    private void setName(
        String value) {
      value.getClass();
  
      name_ = value;
    }
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private String email_;
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The email.
     */
    @Override
    public String getEmail() {
      return email_;
    }
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @param value The email to set.
     */
    private void setEmail(
        String value) {
      value.getClass();
  
      email_ = value;
    }
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();
      
    }

    public static final int NOTIFIC_FIELD_NUMBER = 4;
    private NotificationApi.Notification notific_;
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    @Override
    public boolean hasNotific() {
      return notific_ != null;
    }
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    @Override
    public NotificationApi.Notification getNotific() {
      return notific_ == null ? NotificationApi.Notification.getDefaultInstance() : notific_;
    }
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    private void setNotific(NotificationApi.Notification value) {
      value.getClass();
  notific_ = value;
      
      }
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeNotific(NotificationApi.Notification value) {
      value.getClass();
  if (notific_ != null &&
          notific_ != NotificationApi.Notification.getDefaultInstance()) {
        notific_ =
          NotificationApi.Notification.newBuilder(notific_).mergeFrom(value).buildPartial();
      } else {
        notific_ = value;
      }
      
    }
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    private void clearNotific() {  notific_ = null;
      
    }

    public static UserApi.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserApi.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserApi.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserApi.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserApi.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserApi.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserApi.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserApi.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserApi.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UserApi.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserApi.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserApi.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UserApi.User prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * User contains all the personal details we know about the user.
     * </pre>
     *
     * Protobuf type {@code user.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UserApi.User, Builder> implements
        // @@protoc_insertion_point(builder_implements:user.User)
        UserApi.UserOrBuilder {
      // Construct using user.UserApi.User.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      @Override
      public String getName() {
        return instance.getName();
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @return The email.
       */
      @Override
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      @Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      @Override
      public boolean hasNotific() {
        return instance.hasNotific();
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      @Override
      public NotificationApi.Notification getNotific() {
        return instance.getNotific();
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder setNotific(NotificationApi.Notification value) {
        copyOnWrite();
        instance.setNotific(value);
        return this;
        }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder setNotific(
          NotificationApi.Notification.Builder builderForValue) {
        copyOnWrite();
        instance.setNotific(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder mergeNotific(NotificationApi.Notification value) {
        copyOnWrite();
        instance.mergeNotific(value);
        return this;
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder clearNotific() {  copyOnWrite();
        instance.clearNotific();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:user.User)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UserApi.User();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "id_",
              "name_",
              "email_",
              "notific_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0004\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UserApi.User> parser = PARSER;
          if (parser == null) {
            synchronized (UserApi.User.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UserApi.User>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:user.User)
    private static final UserApi.User DEFAULT_INSTANCE;
    static {
      User defaultInstance = new User();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        User.class, defaultInstance);
    }

    public static UserApi.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<User> PARSER;

    public static com.google.protobuf.Parser<User> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
