// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user_extended.proto

package com.example.asdfprotoproducer.java.user;

public final class UserExtendedOuterClass {
  private UserExtendedOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserExtendedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UserExtended)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * User = User. Required. Contains the user's name and email.
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <pre>
     * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * <pre>
   * UserExtended contains all the personal details we know about the user.
   * </pre>
   *
   * Protobuf type {@code user.UserExtended}
   */
  public  static final class UserExtended extends
      com.google.protobuf.GeneratedMessageLite<
          UserExtended, UserExtended.Builder> implements
      // @@protoc_insertion_point(message_implements:user.UserExtended)
      UserExtendedOrBuilder {
    private UserExtended() {
    }
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <pre>
     * User = User. Required. Contains the user's name and email.
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * User = User. Required. Contains the user's name and email.
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     * @param value The userId to set.
     */
    private void setUserId(int value) {
      
      userId_ = value;
    }
    /**
     * <pre>
     * User = User. Required. Contains the user's name and email.
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     */
    private void clearUserId() {
      
      userId_ = 0;
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }
    /**
     * <pre>
     * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     */
    private void setAge(int value) {
      
      age_ = value;
    }
    /**
     * <pre>
     * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 age = 2;</code>
     */
    private void clearAge() {
      
      age_ = 0;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <pre>
     * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    @Override
    public int getHeight() {
      return height_;
    }
    /**
     * <pre>
     * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 height = 3;</code>
     * @param value The height to set.
     */
    private void setHeight(int value) {
      
      height_ = value;
    }
    /**
     * <pre>
     * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 height = 3;</code>
     */
    private void clearHeight() {
      
      height_ = 0;
    }

    public static UserExtendedOuterClass.UserExtended parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserExtendedOuterClass.UserExtended parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UserExtendedOuterClass.UserExtended parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UserExtendedOuterClass.UserExtended prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * UserExtended contains all the personal details we know about the user.
     * </pre>
     *
     * Protobuf type {@code user.UserExtended}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UserExtendedOuterClass.UserExtended, Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UserExtended)
        UserExtendedOuterClass.UserExtendedOrBuilder {
      // Construct using user.UserExtendedOuterClass.UserExtended.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * User = User. Required. Contains the user's name and email.
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return instance.getUserId();
      }
      /**
       * <pre>
       * User = User. Required. Contains the user's name and email.
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <pre>
       * User = User. Required. Contains the user's name and email.
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <pre>
       * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @Override
      public int getAge() {
        return instance.getAge();
      }
      /**
       * <pre>
       * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        copyOnWrite();
        instance.setAge(value);
        return this;
      }
      /**
       * <pre>
       * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        copyOnWrite();
        instance.clearAge();
        return this;
      }

      /**
       * <pre>
       * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 height = 3;</code>
       * @return The height.
       */
      @Override
      public int getHeight() {
        return instance.getHeight();
      }
      /**
       * <pre>
       * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        copyOnWrite();
        instance.setHeight(value);
        return this;
      }
      /**
       * <pre>
       * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        copyOnWrite();
        instance.clearHeight();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:user.UserExtended)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UserExtendedOuterClass.UserExtended();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "userId_",
              "age_",
              "height_",
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UserExtendedOuterClass.UserExtended> parser = PARSER;
          if (parser == null) {
            synchronized (UserExtendedOuterClass.UserExtended.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UserExtendedOuterClass.UserExtended>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:user.UserExtended)
    private static final UserExtendedOuterClass.UserExtended DEFAULT_INSTANCE;
    static {
      UserExtended defaultInstance = new UserExtended();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserExtended.class, defaultInstance);
    }

    public static UserExtendedOuterClass.UserExtended getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserExtended> PARSER;

    public static com.google.protobuf.Parser<UserExtended> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
