// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user/user_api.proto

// Protobuf Java Version: 3.25.1
package com.example.asdfprotoproducer.java.user;

public final class UserApi {
  private UserApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     * @return Whether the notific field is set.
     */
    boolean hasNotific();
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     * @return The notific.
     */
    com.example.asdfprotoproducer.java.notification.NotificationApi.Notification getNotific();
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    com.example.asdfprotoproducer.java.notification.NotificationApi.NotificationOrBuilder getNotificOrBuilder();
  }
  /**
   * <pre>
   * User contains all the personal details we know about the user.
   * </pre>
   *
   * Protobuf type {@code user.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.asdfprotoproducer.java.user.UserApi.internal_static_user_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.asdfprotoproducer.java.user.UserApi.internal_static_user_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.asdfprotoproducer.java.user.UserApi.User.class, com.example.asdfprotoproducer.java.user.UserApi.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Email. Required. Receipts will be sent to this email.
     * </pre>
     *
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTIFIC_FIELD_NUMBER = 4;
    private com.example.asdfprotoproducer.java.notification.NotificationApi.Notification notific_;
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     * @return Whether the notific field is set.
     */
    @java.lang.Override
    public boolean hasNotific() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     * @return The notific.
     */
    @java.lang.Override
    public com.example.asdfprotoproducer.java.notification.NotificationApi.Notification getNotific() {
      return notific_ == null ? com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.getDefaultInstance() : notific_;
    }
    /**
     * <pre>
     * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
     * </pre>
     *
     * <code>.notification.Notification notific = 4;</code>
     */
    @java.lang.Override
    public com.example.asdfprotoproducer.java.notification.NotificationApi.NotificationOrBuilder getNotificOrBuilder() {
      return notific_ == null ? com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.getDefaultInstance() : notific_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getNotific());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNotific());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.asdfprotoproducer.java.user.UserApi.User)) {
        return super.equals(obj);
      }
      com.example.asdfprotoproducer.java.user.UserApi.User other = (com.example.asdfprotoproducer.java.user.UserApi.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (hasNotific() != other.hasNotific()) return false;
      if (hasNotific()) {
        if (!getNotific()
            .equals(other.getNotific())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasNotific()) {
        hash = (37 * hash) + NOTIFIC_FIELD_NUMBER;
        hash = (53 * hash) + getNotific().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.asdfprotoproducer.java.user.UserApi.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.asdfprotoproducer.java.user.UserApi.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.asdfprotoproducer.java.user.UserApi.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.asdfprotoproducer.java.user.UserApi.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * User contains all the personal details we know about the user.
     * </pre>
     *
     * Protobuf type {@code user.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.User)
        com.example.asdfprotoproducer.java.user.UserApi.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.asdfprotoproducer.java.user.UserApi.internal_static_user_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.asdfprotoproducer.java.user.UserApi.internal_static_user_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.asdfprotoproducer.java.user.UserApi.User.class, com.example.asdfprotoproducer.java.user.UserApi.User.Builder.class);
      }

      // Construct using com.example.asdfprotoproducer.java.user.UserApi.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNotificFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        email_ = "";
        notific_ = null;
        if (notificBuilder_ != null) {
          notificBuilder_.dispose();
          notificBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.asdfprotoproducer.java.user.UserApi.internal_static_user_User_descriptor;
      }

      @java.lang.Override
      public com.example.asdfprotoproducer.java.user.UserApi.User getDefaultInstanceForType() {
        return com.example.asdfprotoproducer.java.user.UserApi.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.asdfprotoproducer.java.user.UserApi.User build() {
        com.example.asdfprotoproducer.java.user.UserApi.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.asdfprotoproducer.java.user.UserApi.User buildPartial() {
        com.example.asdfprotoproducer.java.user.UserApi.User result = new com.example.asdfprotoproducer.java.user.UserApi.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.asdfprotoproducer.java.user.UserApi.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.email_ = email_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.notific_ = notificBuilder_ == null
              ? notific_
              : notificBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.asdfprotoproducer.java.user.UserApi.User) {
          return mergeFrom((com.example.asdfprotoproducer.java.user.UserApi.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.asdfprotoproducer.java.user.UserApi.User other) {
        if (other == com.example.asdfprotoproducer.java.user.UserApi.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasNotific()) {
          mergeNotific(other.getNotific());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getNotificFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name = First-name. Required. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Email. Required. Receipts will be sent to this email.
       * </pre>
       *
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.example.asdfprotoproducer.java.notification.NotificationApi.Notification notific_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.asdfprotoproducer.java.notification.NotificationApi.Notification, com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.Builder, com.example.asdfprotoproducer.java.notification.NotificationApi.NotificationOrBuilder> notificBuilder_;
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       * @return Whether the notific field is set.
       */
      public boolean hasNotific() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       * @return The notific.
       */
      public com.example.asdfprotoproducer.java.notification.NotificationApi.Notification getNotific() {
        if (notificBuilder_ == null) {
          return notific_ == null ? com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.getDefaultInstance() : notific_;
        } else {
          return notificBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder setNotific(com.example.asdfprotoproducer.java.notification.NotificationApi.Notification value) {
        if (notificBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notific_ = value;
        } else {
          notificBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder setNotific(
          com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.Builder builderForValue) {
        if (notificBuilder_ == null) {
          notific_ = builderForValue.build();
        } else {
          notificBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder mergeNotific(com.example.asdfprotoproducer.java.notification.NotificationApi.Notification value) {
        if (notificBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            notific_ != null &&
            notific_ != com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.getDefaultInstance()) {
            getNotificBuilder().mergeFrom(value);
          } else {
            notific_ = value;
          }
        } else {
          notificBuilder_.mergeFrom(value);
        }
        if (notific_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public Builder clearNotific() {
        bitField0_ = (bitField0_ & ~0x00000008);
        notific_ = null;
        if (notificBuilder_ != null) {
          notificBuilder_.dispose();
          notificBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.Builder getNotificBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getNotificFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      public com.example.asdfprotoproducer.java.notification.NotificationApi.NotificationOrBuilder getNotificOrBuilder() {
        if (notificBuilder_ != null) {
          return notificBuilder_.getMessageOrBuilder();
        } else {
          return notific_ == null ?
              com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.getDefaultInstance() : notific_;
        }
      }
      /**
       * <pre>
       * Notification = Notification. Optional. Will be sent to the user when the cut is ready.
       * </pre>
       *
       * <code>.notification.Notification notific = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.asdfprotoproducer.java.notification.NotificationApi.Notification, com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.Builder, com.example.asdfprotoproducer.java.notification.NotificationApi.NotificationOrBuilder> 
          getNotificFieldBuilder() {
        if (notificBuilder_ == null) {
          notificBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.asdfprotoproducer.java.notification.NotificationApi.Notification, com.example.asdfprotoproducer.java.notification.NotificationApi.Notification.Builder, com.example.asdfprotoproducer.java.notification.NotificationApi.NotificationOrBuilder>(
                  getNotific(),
                  getParentForChildren(),
                  isClean());
          notific_ = null;
        }
        return notificBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:user.User)
    }

    // @@protoc_insertion_point(class_scope:user.User)
    private static final com.example.asdfprotoproducer.java.user.UserApi.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.asdfprotoproducer.java.user.UserApi.User();
    }

    public static com.example.asdfprotoproducer.java.user.UserApi.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.asdfprotoproducer.java.user.UserApi.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/user/user_api.proto\022\004user\032\036proto" +
      "/user/user_extended.proto\032)proto/notific" +
      "ation/notification_api.proto\"\\\n\004User\022\n\n\002" +
      "id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022+\n" +
      "\007notific\030\004 \001(\0132\032.notification.Notificati" +
      "on2\255\002\n\013UserService\022\"\n\006Create\022\n.user.User" +
      "\032\n.user.User\"\000\022\"\n\006Update\022\n.user.User\032\n.u" +
      "ser.User\"\000\022\"\n\006Delete\022\n.user.User\032\n.user." +
      "User\"\000\022:\n\016CreateExtended\022\022.user.UserExte" +
      "nded\032\022.user.UserExtended\"\000\022:\n\016UpdateExte" +
      "nded\022\022.user.UserExtended\032\022.user.UserExte" +
      "nded\"\000\022:\n\016DeleteExtended\022\022.user.UserExte" +
      "nded\032\022.user.UserExtended\"\000B)\n\'com.exampl" +
      "e.asdfprotoproducer.java.userb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.getDescriptor(),
          com.example.asdfprotoproducer.java.notification.NotificationApi.getDescriptor(),
        });
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Notific", });
    com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.getDescriptor();
    com.example.asdfprotoproducer.java.notification.NotificationApi.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
