// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user/user_extended.proto

// Protobuf Java Version: 3.25.1
package com.example.asdfprotoproducer.java.user;

public final class UserExtendedOuterClass {
  private UserExtendedOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserExtendedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UserExtended)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * User = User. Required. Contains the user's name and email.
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <pre>
     * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * <pre>
   * UserExtended contains all the personal details we know about the user.
   * </pre>
   *
   * Protobuf type {@code user.UserExtended}
   */
  public static final class UserExtended extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.UserExtended)
      UserExtendedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserExtended.newBuilder() to construct.
    private UserExtended(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserExtended() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserExtended();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.internal_static_user_UserExtended_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.internal_static_user_UserExtended_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.class, com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_ = 0;
    /**
     * <pre>
     * User = User. Required. Contains the user's name and email.
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_ = 0;
    /**
     * <pre>
     * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_ = 0;
    /**
     * <pre>
     * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
     * </pre>
     *
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (height_ != 0) {
        output.writeInt32(3, height_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended)) {
        return super.equals(obj);
      }
      com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended other = (com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * UserExtended contains all the personal details we know about the user.
     * </pre>
     *
     * Protobuf type {@code user.UserExtended}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UserExtended)
        com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtendedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.internal_static_user_UserExtended_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.internal_static_user_UserExtended_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.class, com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.Builder.class);
      }

      // Construct using com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0;
        age_ = 0;
        height_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.internal_static_user_UserExtended_descriptor;
      }

      @java.lang.Override
      public com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended getDefaultInstanceForType() {
        return com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended build() {
        com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended buildPartial() {
        com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended result = new com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.height_ = height_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended) {
          return mergeFrom((com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended other) {
        if (other == com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                height_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <pre>
       * User = User. Required. Contains the user's name and email.
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * User = User. Required. Contains the user's name and email.
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * User = User. Required. Contains the user's name and email.
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Age. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <pre>
       * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 height = 3;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <pre>
       * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {

        height_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Height. Optional. Will be displayed on the monitors in the salon when purchasing a cut.
       * </pre>
       *
       * <code>int32 height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:user.UserExtended)
    }

    // @@protoc_insertion_point(class_scope:user.UserExtended)
    private static final com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended();
    }

    public static com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserExtended>
        PARSER = new com.google.protobuf.AbstractParser<UserExtended>() {
      @java.lang.Override
      public UserExtended parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserExtended> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserExtended> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.asdfprotoproducer.java.user.UserExtendedOuterClass.UserExtended getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserExtended_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserExtended_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/user/user_extended.proto\022\004user\";" +
      "\n\014UserExtended\022\016\n\006userId\030\001 \001(\005\022\013\n\003age\030\002 " +
      "\001(\005\022\016\n\006height\030\003 \001(\005B)\n\'com.example.asdfp" +
      "rotoproducer.java.userb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_UserExtended_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_UserExtended_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserExtended_descriptor,
        new java.lang.String[] { "UserId", "Age", "Height", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
